### ISSUE TITLE
How install and run this proxy on PC?

### ISSUE THREAD

**Issue by Symbian9** [pasutisu/poseidon2#1]
Please, add more info about this application in project README.md file (in English).
How it work and what external dependency it have?

**Comment by pasutisu** [comment]
It needs only Python3(depended to only standard libs).
To running, type following command.
`python3 src/main.py`

And currently it is only a proxy... But in weekend, I will implement client carrier landing!
(English documents wait soon)

**Comment by Symbian9** [comment]
Ok, now I can launch it on Linux.
So, see only ASCII art, version disclamer and next string:
<code>Poseidon: Listening started.</code>
So, what do next?

**Comment by pasutisu** [comment]
Please read code(currently it is very simple).
